packages:
  - layers/auth
  - layers/admin
  - packages/i18n
  - packages/ui

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  unrs-resolver: true
  vue-demi: true

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - unrs-resolver
  - vue-demi
